### ISSUE TITLE
Create new resource from OCR data - missing types and fields

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#146]
When creating a new resource from OCR data, there are only three types of resources available: Monograph, collection and journal. We need at least journal article and book chapter, too. For journal articles, it must be possibly to specify the journal title, volume, issue, and pages. In the data model document, we have the following:
•	is part of: bibliographic resource (br)
The corpus identifier of the bibliographic resource (e.g. issue, volume, journal, conference proceedings) that is a container for the subject bibliographic resource.
How should we enter this information in the frontend?

**Comment by lgalke** [comment]
The partOf field was removed from being editable. The rationale was that the intended value of this field is to be a locdb internal identifer `resource._id` (See #145 what happens when its editable). It is crucial to the internal data structure and you are not allowed to put anything else in there than `resource._id`s which are unknown from the user's perspective.

One solution would be to pop-up autocompletion with basically the internal suggestions, and then, behind the scenes, enter the `_id` of the selected one. 

Unfortunately, this is not possible before the workshop. The complexity of linking one resource to another in a `partOf` relationship is about the same as the complexity of linking a bibliographic reference (=entry) to another resource. Thus, you would need the whole right-hand-side of suggestions just to fill this field, without given `entry` information.

For the workshop I think its fair to explain that this is (as above) would be our intended solution (we are presenting work-in-progress). Hope that you agree.

**Comment by lgalke** [comment]
Apart from the `partOf` issue, is the list of resource types (currently: `MONOGRAPH`, `JOURNAL`, `COLLECTION`) complete?

**Comment by lgalke** [comment]
Journal Article, Bookchapter

**Comment by anlausch** [comment]
As a long term solution, we will try to use the Open Citations types. Therefore, we will work on a proper mapping also between the workflow paths and those resource types.

**Comment by zuphilip** [comment]
From the discussion: Add `container-title` field (maybe until workshop) as a *free* string field. But possibly postpone this after the workshop.

Please also add the publication year for external suggestions from CrossRef.

**Comment by anlausch** [comment]
@zuphilip Crossref provides several dates and I am not 100% sure which one to take. Could you help out? The following dates are available and filled for most of the examples I have seen:

created (not relevant?)
deposited (not relevant?)
indexed (not relevant?)
issued (relevant?)
published-online (relevant?)
published-print (relevant?)

**Comment by kleinann** [comment]
I'd say published-online and published-print - both, if both are filled.

**Comment by anlausch** [comment]
Unfortunately, the OpenCitations data model only offers one field, publicationYear, which is directly attached to the bibliographic resource. I can just put both as a string into that field, but that might be confusing and cause inconsistencies. Any ideas from the others?

**Comment by anlausch** [comment]
Status Quo: A field was added to our data model `containerTitle`. I am still thinking whether this is a good solution as we do not want to change the OpenCitations data model too much. For now, it's ok. 
This field can be exposed to the user. When parsing data from Crossref, the field is filled with the `container-title` given.

**Comment by lgalke** [comment]
For now the solution seems to be a reasonable choice. The benefit is that we do not completely lose the information about the collection, when there is no real *link* (i.e. ´partOf´). Thus a proper disambiguation would be at least possible later. For RDF exports we can always ignore such a property so that we retain compatibility to the OC model.

**Comment by kleinann** [comment]
Is it possible that this influences the presentation of the entry list originating from Crossref also? I just loaded a new article, "Rethinking Compassion: Toward a Political Account of the Partisan Gender Gap in the United States", and the entry list doesn't show anything but dates and titles anymore.

**Comment by kleinann** [comment]
A new bug: "Type" is now automatically filled with the subtitle in the citing resources.

**Comment by lgalke** [comment]
a69fc1a also exposes `containerTitle` in the bibliographic resource form.

**Comment by lgalke** [comment]
> A new bug: "Type" is now automatically filled with the subtitle in the citing resources.

At which point exactly? Meta-data from crossref?

**Comment by lgalke** [comment]
> Is it possible that this influences the presentation of the entry list originating from Crossref also?

The rule for the *short* (collapsed) presentation of an entry in any entry-list is:

**If** there is a title information available, show the title, **else** show the full bibliographicEntryText (raw)

If there is a better suggestion, it can be changed quickly.

**Comment by kleinann** [comment]
Todo management --> External
![grafik](https://user-images.githubusercontent.com/33151732/32376652-af98f4f0-c0a5-11e7-984b-81f7100a61f8.png)

**Comment by lgalke** [comment]
Ohh thats what you mean. I will create an issue for it and try to fix it later in the afternoon.

**Comment by kleinann** [comment]
For the other point: It's ok to show the title in the collapsed view, but there's nothing but title and date even in the detailed view:
![grafik](https://user-images.githubusercontent.com/33151732/32376826-3bbca134-c0a6-11e7-85b2-ebb111a01056.png)

although there's more data at crossref:
https://api.crossref.org/works/10.1111/pops.12447

**Comment by anlausch** [comment]
The subtitle as type bug is fixed.

**Comment by anlausch** [comment]
More details are now retrieved from crossref references.

**Comment by kleinann** [comment]
Now the title is missing in the "External" to do list:

![grafik](https://user-images.githubusercontent.com/33151732/32386490-b4f120a0-c0c1-11e7-9e0f-5a6f2d4c0559.png)

**Comment by kleinann** [comment]
DOI is still missing in crossref references. 
Example: Article "Reluctant entrepreneurs: musicians and entrepreneurship in the ‘new’ music industry"
Second reference - data in Crossref:
    "issue": "3",
    "key": "10.1111/1468-4446.12286-BIB0002|bjos12286-cit-0002",
    "doi-asserted-by": "crossref",
    "first-page": "455",
    "DOI": "10.1177/0038038506063669",
    "article-title": "Moral Economy and Cultural Work",
    "volume": "40",
    "author": "Banks",
    "year": "2006",
    "journal-title": "Sociology"

The same in List of entries:
![grafik](https://user-images.githubusercontent.com/33151732/32386834-c9390a90-c0c2-11e7-9ca5-8d597dd62bf3.png)

The resource isn't found in External suggestions, although it comes with a DOI in the original metadata.

**Comment by kleinann** [comment]
#151

**Comment by lgalke** [comment]
Now the meta-data of bibliographic entry is only shown if it is filled with something (as in the resource details view).

**Comment by lgalke** [comment]
In the example above, the title field is empty and therefore not displayed.

**Comment by kleinann** [comment]
The Crossref data looks like this:

title |  
-- | --
0 | "Reluctant entrepreneurs: musicians and entrepreneurship in the ‘new’ music industry"
prefix | "10.1111"
author |  
0 |  
given | "Jo"
family | "Haynes"
etc.

I can't see the difference between this and the following, where the title is displayed:

title |  
-- | --
0 | "The unintended consequences in new economic sociology: Why still not taken seriously?"
prefix | "10.1177"
author |  
0 |  
given | "Adriana"
family | "Mica"
etc.

**Comment by lgalke** [comment]
Is only the single example affected, or are there more? There is of course the possibility that someone edited and removed the title. Does the bug occur right after upload already?

**Comment by anlausch** [comment]
Which doi is it?

**Comment by zuphilip** [comment]
AFAIK https://doi.org/10.1111/1468-4446.12286 (and https://10.1177/0539018417734322 )

**Comment by anlausch** [comment]
Regarding the first example by @zuphilip. Below you see the references that can be retrieved via crossref. For the first reference, the only title available is given is the field "volume-title". Therefore, the back end saved this title in the property volume (similarly journal-title is saved in journal). The front end is not checking this field (as I assume). I quickly adapted it (now saving volume-title in title when article-title is not given) such that it looks nicer at the workshop. But for longterm enhancement: which place to save would be the correct one?

"reference":[  
         {  
            "key":"10.1111\/1468-4446.12286-BIB0001|bjos12286-cit-0001",
            "author":"Anderson",
            "year":"2007",
            "volume-title":"The Long Tail: How Endless Choice Is Creating Unlimited Demand"
         },
         {  
            "issue":"3",
            "key":"10.1111\/1468-4446.12286-BIB0002|bjos12286-cit-0002",
            "doi-asserted-by":"crossref",
            "first-page":"455",
            "DOI":"10.1177\/0038038506063669",
            "article-title":"Moral Economy and Cultural Work",
            "volume":"40",
            "author":"Banks",
            "year":"2006",
            "journal-title":"Sociology"
         },

**Comment by zuphilip** [comment]
> I quickly adapted it (now saving volume-title in title when article-title is not given) such that it looks nicer at the workshop. But for longterm enhancement: which place to save would be the correct one?

Sounds good for now. AFAIS this example is a book and therefore this is simply the title of the book (not sure how to model that correctly). After the workshop, we should also check how OpenCitations deals with CrossRef citations.

**Comment by lgalke** [comment]
The entry view and form is aware of the properties `ocrData.journal` and `ocrData.volume`, however they are not considered for the short text of an entry.

**Comment by lgalke** [comment]
The conversion from an entry to a **new** local resource was improved in 304748b

- `ocrData.journal` maps to `containerTitle`
- `ocrData.volume` maps to `number`
- `identifiers` map to `identifiers`

**Comment by anlausch** [comment]
Implementation hierarchy for publication dates: Issued --> Print --> Online

**Comment by lgalke** [comment]
The discussion in this issue diverged. For some of the discussed problems, are now more specific issues such as #202 .

**Comment by zuphilip** [comment]
Another aspect is discussed further in #199.
