### ISSUE TITLE
Uploading pdfs via DOI

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#307]
Because we talked about it earlier, I checked if I can upload journal article pdf files via DOI. First of all, I noticed, that the DOI is not automatically ingested in the DOI field.
![2018-05-25 uploadpdfejournal2](https://user-images.githubusercontent.com/32642653/40542269-cf5fef72-601f-11e8-91dc-44bad36e8746.png)
After manually filling in the DOI field and changing the embodiment type to "digital" I get an error.
![2018-05-25 uploadpdfejournal4](https://user-images.githubusercontent.com/32642653/40542975-a8800100-6022-11e8-9c83-57c316834582.png)

I checked with every combination of print vs digital and textual pdf or not. Nothing seems to work.
I cleared my cache and checked again and nothing helped. Any ideas?!

**Comment by anlausch** [comment]
The problem in the back end is that a resource with this doi does not exist in any of our external sources. I will provide a fix in the next hours.

**Comment by anlausch** [comment]
For resource type JOURNAL_ARTICLE, this problem should be fixed. But I leave the issue open as the second  part of this issue (doi extraction) is a front end functionality.

**Comment by LauraErhard** [comment]
The uploading works now. Thank you!

But after that I immediately see the entry in the external part AND in the OCR_Processing part, would it be possible to label the pdf (in the external part) while it is still getting processed? Because if you click on the link to the scan view it only shows this:
![2018-05-28 scanview_doi_nothing](https://user-images.githubusercontent.com/32642653/40607792-cb43d2ea-6269-11e8-8c69-66697545e369.png)
Or maybe you can change the `Received application-type` message to `the scan is still being processed` or something to this extend?! Then the user knows to just wait a little bit and check later.

We got some articles stuck in the OCR_processing part and therefore a curious thing happens in the 'external' scan view:
![2018-05-28 scanview_doi](https://user-images.githubusercontent.com/32642653/40607987-59f5e046-626a-11e8-9771-a5a4f937a6c0.png)
It looks like the data is processed but the scan cannot be loaded. Maybe this problem goes away with the new OCR model but I just wanted to document it here for now.

**Comment by lgalke** [comment]
Until now, there is only PPN extraction implemented. We can add DOI support aswell, soon.

```
/^10.\d{4,9}/[-._;()/:A-Z0-9]+$/i
```

**Comment by lgalke** [comment]
Regarding the other problem, @anlausch do PDFs uploaded by DOI properly get converted to PNG?

**Comment by anlausch** [comment]
I agree that the status should be set differently in that case and I will try to come up with a better solution.

**Comment by LauraErhard** [comment]
I just realized that for PDFs uploaded by DOI there is always a new container resource (journal issue) created, because we do not have metadata in these cases and the system can't identify articles which are from the same issue. 
Have we thought about this scenario? 
Do we have to manually add all the information to every container (this would be quite tedious).
Or is there a possibility to link them all together somehow?!
For example, the following 3 articles are all from the same journal and issue, but all have a unique container resource:
![2018-05-28 toomanyjournalissues](https://user-images.githubusercontent.com/32642653/40613383-9ccf0f0a-627e-11e8-9c2f-eeeef1a6a688.png)
What do we do in these cases?!

**Comment by anlausch** [comment]
Regarding your comment @lgalke: The problem in that case is not a missing conversion to png (as the scan is still being processed there is no converted file YET). The problem is threefold:
1) The resource has two status a) EXTERNAL because it was created with the same mechanism as all the resources for which we retrieve external references (imagine also a case in which there are indeed references coming from crossref, but the user uploads a scan anyways). b) OCR_PROCESSING because a scan was uploaded, which is being processed. @kleinann @LauraErhard @zuphilip What do you think? In my opinion that's  -- in principal -- technically correct. How would you like those cases to be handled? I agree that if there are no references coming from crossref we can apply the scan status to the whole resource.
2) The second problem (if I understood correctly) is a front end problem. If a scan is still being processed and the scan can not be displayed because of that, we should show an appropriate message to the user or apply another mechansism that does not cause confusion.
3) The third problem is how to handle the case described above: We have no metadata for the parent, so I cannot link newly created children automatically to the corresponding container. I would maybe propose to add a separate service for saving child resources to already available containers. What do you think @lgalke?

**Comment by anlausch** [comment]
Relating to the first problem we also have to keep in mind that there could be the case that the user creates a resource via doi, no references and meta data can be retrieved BUT the user also doesn't upload a scan at the same time, which is why I need to set the status EXTERNAL (it has to be visible in the todos).

**Comment by lgalke** [comment]
1. At some point, we might think about simplifying those things again. Does it really matter whether the   container was first ingested by a scan upload or a pure DOI lookup? At the current state, we do try to retrieve meta-data also for uploaded scans and we are able to attach scans to existing resources.  When the **resource** itself is flagged by `OCR_*PROCESS*`, it is also not clear, to which scan of which embodiment this refers to. The only thing, on the resource level, that matters is: `hasAtLeastOneUnresolvedReferenceSomewhere: bool`, which triggers visibility as a todo item on the agenda. So we might reconsider the status of resources.. What are your thoughts on that @anlausch ? 

2. Yes, we can presumably fix that in the front-end.

3. So CrossRef does not provide something like `partof` links? That's too bad and would then require human effort. To make this possible, there are several options but right now I cannot think of any that is both easy-to-use and stable. Probably, it would be something like making the `partOf` property editable and provide auto-completions based on querying for internal resources.

**Comment by anlausch** [comment]
Just to clarify regarding 3. : Usually crossref provides everything we need, but sometimes a resource is not in crossref and we cannot automatically retrieve meta data at all. In that case, we anyways need human effort.

> Probably, it would be something like making the partOf property editable and provide auto-completions based on querying for internal resources.

That could be a solution.

**Comment by LauraErhard** [comment]
Regarding 3 would it be possible for us to just provide an identifier (ISSN or ZDB-ID) for the container and then somehow trigger another metadata check in SWB/ZDB? Or would this be an unreasonable complicated functionality and we have to just copy and paste the information (hopefully just once for every issue).

**Comment by lgalke** [comment]
We now do have DOI extraction from filenames.

**Comment by lgalke** [comment]
We also have the Autocompletion for changing the `partOf` relationship now. Do you think the additional field for container id within the Ingest view is still required @LauraErhard ?

**Comment by LauraErhard** [comment]
If the autocompletion and the editing of parents/adding new parents (#326) works perfectly we don't need the container ID. But maybe we should keep this issue open until then. What do you think?

**Comment by lgalke** [comment]
>If the autocompletion and the editing of parents/adding new parents (#326) works perfectly we don't need the container ID. But maybe we should keep this issue open until then. What do you think?

I deliberately claim that those two things now work perfectly. ;)
